// HomeLog - Home Inventory
(function() {
    'use strict';

    const i18n = {
        en: {
            rooms:'Rooms', summary:'Summary', total_value:'Total Value',
            add_room:'Add Room', room_name:'Room Name', room_icon:'Icon',
            save:'Save', add_item:'Add Item', edit_item:'Edit Item',
            item_name:'Item Name', purchase_price:'Price', purchase_date:'Date',
            brand_model:'Brand / Model', serial_number:'Serial No.',
            photo:'Photo', tap_to_add_photo:'Tap to add photo',
            notes:'Notes', items:'items', select_language:'Language',
            no_rooms:'No rooms yet. Tap + to add your first room.',
            no_items:'No items in this room. Tap + to add.',
            room_total:'Room Total', grand_total:'Grand Total',
            item_count:'Item Count', export_title:'Home Inventory Report',
            export_date:'Date', export_generated:'Generated by HomeLog'
        },
        zh: {
            rooms:'\u623f\u95f4', summary:'\u6458\u8981', total_value:'\u603b\u4ef7\u503c',
            add_room:'\u6dfb\u52a0\u623f\u95f4', room_name:'\u623f\u95f4\u540d\u79f0', room_icon:'\u56fe\u6807',
            save:'\u4fdd\u5b58', add_item:'\u6dfb\u52a0\u7269\u54c1', edit_item:'\u7f16\u8f91\u7269\u54c1',
            item_name:'\u7269\u54c1\u540d\u79f0', purchase_price:'\u8d2d\u4e70\u4ef7\u683c', purchase_date:'\u8d2d\u4e70\u65e5\u671f',
            brand_model:'\u54c1\u724c/\u578b\u53f7', serial_number:'\u5e8f\u5217\u53f7',
            photo:'\u7167\u7247', tap_to_add_photo:'\u70b9\u51fb\u6dfb\u52a0\u7167\u7247',
            notes:'\u5907\u6ce8', items:'\u4ef6', select_language:'\u9009\u62e9\u8bed\u8a00',
            no_rooms:'\u8fd8\u6ca1\u6709\u623f\u95f4\uff0c\u70b9\u51fb+\u6dfb\u52a0\u3002',
            no_items:'\u6b64\u623f\u95f4\u8fd8\u6ca1\u6709\u7269\u54c1\uff0c\u70b9\u51fb+\u6dfb\u52a0\u3002',
            room_total:'\u623f\u95f4\u5c0f\u8ba1', grand_total:'\u603b\u8ba1',
            item_count:'\u7269\u54c1\u6570\u91cf', export_title:'\u5bb6\u5ead\u8d22\u4ea7\u6e05\u5355',
            export_date:'\u65e5\u671f', export_generated:'\u7531 HomeLog \u751f\u6210'
        },
        es: {
            rooms:'Habitaciones', summary:'Resumen', total_value:'Valor Total',
            add_room:'A\u00f1adir habitaci\u00f3n', room_name:'Nombre', room_icon:'Icono',
            save:'Guardar', add_item:'A\u00f1adir art\u00edculo', edit_item:'Editar',
            item_name:'Nombre', purchase_price:'Precio', purchase_date:'Fecha',
            brand_model:'Marca / Modelo', serial_number:'N\u00ba Serie',
            photo:'Foto', tap_to_add_photo:'Toca para a\u00f1adir foto',
            notes:'Notas', items:'art\u00edculos', select_language:'Idioma',
            no_rooms:'Sin habitaciones. Pulsa + para a\u00f1adir.',
            no_items:'Sin art\u00edculos. Pulsa + para a\u00f1adir.',
            room_total:'Total habitaci\u00f3n', grand_total:'Total General',
            item_count:'Cantidad', export_title:'Inventario del Hogar',
            export_date:'Fecha', export_generated:'Generado por HomeLog'
        },
        ja: {
            rooms:'\u90e8\u5c4b', summary:'\u30b5\u30de\u30ea\u30fc', total_value:'\u5408\u8a08\u91d1\u984d',
            add_room:'\u90e8\u5c4b\u3092\u8ffd\u52a0', room_name:'\u90e8\u5c4b\u540d', room_icon:'\u30a2\u30a4\u30b3\u30f3',
            save:'\u4fdd\u5b58', add_item:'\u30a2\u30a4\u30c6\u30e0\u8ffd\u52a0', edit_item:'\u7de8\u96c6',
            item_name:'\u54c1\u540d', purchase_price:'\u4fa1\u683c', purchase_date:'\u8cfc\u5165\u65e5',
            brand_model:'\u30d6\u30e9\u30f3\u30c9/\u578b\u756a', serial_number:'\u30b7\u30ea\u30a2\u30eb\u30ca\u30f3\u30d0\u30fc',
            photo:'\u5199\u771f', tap_to_add_photo:'\u30bf\u30c3\u30d7\u3057\u3066\u5199\u771f\u3092\u8ffd\u52a0',
            notes:'\u30e1\u30e2', items:'\u500b', select_language:'\u8a00\u8a9e',
            no_rooms:'\u90e8\u5c4b\u304c\u3042\u308a\u307e\u305b\u3093\u3002',
            no_items:'\u30a2\u30a4\u30c6\u30e0\u304c\u3042\u308a\u307e\u305b\u3093\u3002',
            room_total:'\u90e8\u5c4b\u5408\u8a08', grand_total:'\u7dcf\u5408\u8a08',
            item_count:'\u30a2\u30a4\u30c6\u30e0\u6570', export_title:'\u30db\u30fc\u30e0\u30a4\u30f3\u30d9\u30f3\u30c8\u30ea',
            export_date:'\u65e5\u4ed8', export_generated:'HomeLog \u3067\u751f\u6210'
        },
        de: {
            rooms:'R\u00e4ume', summary:'\u00dcbersicht', total_value:'Gesamtwert',
            add_room:'Raum hinzuf\u00fcgen', room_name:'Name', room_icon:'Symbol',
            save:'Speichern', add_item:'Gegenstand hinzuf\u00fcgen', edit_item:'Bearbeiten',
            item_name:'Name', purchase_price:'Preis', purchase_date:'Kaufdatum',
            brand_model:'Marke / Modell', serial_number:'Seriennummer',
            photo:'Foto', tap_to_add_photo:'Tippen f\u00fcr Foto',
            notes:'Notizen', items:'St\u00fcck', select_language:'Sprache',
            no_rooms:'Keine R\u00e4ume. + tippen.',
            no_items:'Keine Gegenst\u00e4nde. + tippen.',
            room_total:'Raumtotal', grand_total:'Gesamttotal',
            item_count:'Anzahl', export_title:'Haushaltsinventar',
            export_date:'Datum', export_generated:'Erstellt mit HomeLog'
        },
        fr: {
            rooms:'Pi\u00e8ces', summary:'R\u00e9sum\u00e9', total_value:'Valeur totale',
            add_room:'Ajouter pi\u00e8ce', room_name:'Nom', room_icon:'Ic\u00f4ne',
            save:'Enregistrer', add_item:'Ajouter article', edit_item:'Modifier',
            item_name:'Nom', purchase_price:'Prix', purchase_date:"Date d'achat",
            brand_model:'Marque / Mod\u00e8le', serial_number:'N\u00ba s\u00e9rie',
            photo:'Photo', tap_to_add_photo:'Touchez pour ajouter',
            notes:'Notes', items:'articles', select_language:'Langue',
            no_rooms:'Aucune pi\u00e8ce. Appuyez +.',
            no_items:'Aucun article. Appuyez +.',
            room_total:'Total pi\u00e8ce', grand_total:'Total g\u00e9n\u00e9ral',
            item_count:'Nombre', export_title:'Inventaire du foyer',
            export_date:'Date', export_generated:'G\u00e9n\u00e9r\u00e9 par HomeLog'
        }
    };

    const STORAGE_KEY = 'homelog_data';
    let state = { lang: 'en', rooms: [], items: [] };
    let currentRoomId = null;
    let editingItemId = null;
    let selectedIcon = '\u127968';
    let itemPhotoData = null;

    function load() {
        try {
            const raw = localStorage.getItem(STORAGE_KEY);
            if (raw) state = { ...state, ...JSON.parse(raw) };
        } catch(e) {}
    }

    function save() {
        try { localStorage.setItem(STORAGE_KEY, JSON.stringify(state)); } catch(e) {}
    }

    function t(k) { return (i18n[state.lang] && i18n[state.lang][k]) || i18n.en[k] || k; }

    function applyI18n() {
        document.querySelectorAll('[data-i18n]').forEach(el => {
            el.textContent = t(el.getAttribute('data-i18n'));
        });
    }

    function genId() { return 'id_' + Date.now().toString(36) + Math.random().toString(36).substr(2,4); }

    function fmt(price) {
        return '$' + (price || 0).toFixed(2);
    }

    // === RENDER ROOMS ===
    function renderRooms() {
        const grid = document.getElementById('roomGrid');

        if (state.rooms.length === 0) {
            grid.innerHTML = `<div class="empty-state"><div class="empty-icon">&#127968;</div><p>${t('no_rooms')}</p></div>`;
            return;
        }

        grid.innerHTML = '';
        state.rooms.forEach(room => {
            const roomItems = state.items.filter(i => i.roomId === room.id);
            const total = roomItems.reduce((s, i) => s + (i.price || 0), 0);

            const card = document.createElement('div');
            card.className = 'room-card';
            card.innerHTML = `
                <button class="room-delete" data-id="${room.id}">&times;</button>
                <div class="room-icon">${room.icon}</div>
                <div class="room-name">${room.name}</div>
                <div class="room-meta">${roomItems.length} ${t('items')}</div>
                <div class="room-value">${fmt(total)}</div>
            `;

            card.addEventListener('click', (e) => {
                if (e.target.classList.contains('room-delete')) return;
                currentRoomId = room.id;
                showItemsView();
            });

            card.querySelector('.room-delete').addEventListener('click', (e) => {
                e.stopPropagation();
                if (confirm('Delete "' + room.name + '"?')) {
                    state.rooms = state.rooms.filter(r => r.id !== room.id);
                    state.items = state.items.filter(i => i.roomId !== room.id);
                    save();
                    renderRooms();
                    updateTotal();
                }
            });

            grid.appendChild(card);
        });
    }

    function updateTotal() {
        const total = state.items.reduce((s, i) => s + (i.price || 0), 0);
        document.getElementById('totalValue').textContent = fmt(total);
    }

    // === RENDER ITEMS ===
    function showItemsView() {
        switchView('viewItems');
        renderItems();
    }

    function renderItems() {
        const room = state.rooms.find(r => r.id === currentRoomId);
        if (!room) return;

        document.getElementById('itemsRoomTitle').textContent = room.icon + ' ' + room.name;
        const list = document.getElementById('itemList');
        const items = state.items.filter(i => i.roomId === currentRoomId);

        if (items.length === 0) {
            list.innerHTML = `<div class="empty-state"><div class="empty-icon">&#128230;</div><p>${t('no_items')}</p></div>`;
            return;
        }

        list.innerHTML = '';
        items.forEach(item => {
            const card = document.createElement('div');
            card.className = 'item-card';

            const photoHTML = item.photo
                ? `<img src="${item.photo}" alt="">`
                : '&#128230;';

            card.innerHTML = `
                <button class="item-delete" data-id="${item.id}">&times;</button>
                <div class="item-photo">${photoHTML}</div>
                <div class="item-info">
                    <div class="item-name">${item.name}</div>
                    ${item.brand ? `<div class="item-brand">${item.brand}</div>` : ''}
                    <div class="item-meta-row">
                        ${item.date ? `<span>&#128197; ${item.date}</span>` : ''}
                        ${item.serial ? `<span>&#128274; ${item.serial}</span>` : ''}
                    </div>
                    <div class="item-price">${fmt(item.price)}</div>
                </div>
            `;

            card.addEventListener('click', (e) => {
                if (e.target.classList.contains('item-delete')) return;
                openEditItem(item.id);
            });

            card.querySelector('.item-delete').addEventListener('click', (e) => {
                e.stopPropagation();
                state.items = state.items.filter(i => i.id !== item.id);
                save();
                renderItems();
                updateTotal();
            });

            list.appendChild(card);
        });
    }

    // === SUMMARY ===
    function renderSummary() {
        const chart = document.getElementById('summaryChart');
        const list = document.getElementById('summaryList');

        if (state.rooms.length === 0) {
            chart.innerHTML = `<div class="empty-state"><p>${t('no_rooms')}</p></div>`;
            list.innerHTML = '';
            return;
        }

        const roomData = state.rooms.map(room => {
            const roomItems = state.items.filter(i => i.roomId === room.id);
            const total = roomItems.reduce((s, i) => s + (i.price || 0), 0);
            return { name: room.name, total, count: roomItems.length, icon: room.icon };
        }).filter(r => r.total > 0).sort((a,b) => b.total - a.total);

        const maxVal = Math.max(...roomData.map(r => r.total), 1);
        const colors = ['#92400E','#059669','#2563EB','#7C3AED','#DC2626','#CA8A04','#0D9488','#EA580C'];

        chart.innerHTML = roomData.map((r, idx) => `
            <div class="bar-row">
                <span class="bar-label">${r.icon} ${r.name}</span>
                <div class="bar-track">
                    <div class="bar-fill" style="width:${(r.total/maxVal*100).toFixed(1)}%;background:${colors[idx%colors.length]}"></div>
                </div>
                <span class="bar-value">${fmt(r.total)}</span>
            </div>
        `).join('');

        const grandTotal = state.items.reduce((s, i) => s + (i.price || 0), 0);
        list.innerHTML = `
            <div class="summary-row">
                <span>${t('item_count')}</span>
                <span>${state.items.length}</span>
            </div>
            <div class="summary-row total">
                <span>${t('grand_total')}</span>
                <span>${fmt(grandTotal)}</span>
            </div>
        `;
    }

    // === ADD ROOM ===
    function openAddRoom() {
        document.getElementById('inputRoomName').value = '';
        selectedIcon = '\u127968';
        updateIconSelection();
        document.getElementById('modalAddRoom').style.display = 'flex';
    }

    function updateIconSelection() {
        document.querySelectorAll('.icon-opt').forEach(opt => {
            const ic = opt.getAttribute('data-icon');
            opt.classList.toggle('selected', ic === selectedIcon);
        });
    }

    function saveRoom() {
        const name = document.getElementById('inputRoomName').value.trim();
        if (!name) return;
        state.rooms.push({ id: genId(), name, icon: selectedIcon });
        save();
        renderRooms();
        document.getElementById('modalAddRoom').style.display = 'none';
    }

    // === ADD / EDIT ITEM ===
    function openAddItem() {
        editingItemId = null;
        itemPhotoData = null;
        document.getElementById('itemModalTitle').textContent = t('add_item');
        document.getElementById('inputItemName').value = '';
        document.getElementById('inputItemPrice').value = '';
        document.getElementById('inputItemDate').value = '';
        document.getElementById('inputItemBrand').value = '';
        document.getElementById('inputItemSerial').value = '';
        document.getElementById('inputItemNotes').value = '';
        document.getElementById('photoPreview').style.display = 'none';
        document.getElementById('photoPreview').src = '';
        document.querySelector('#photoUploadArea span').style.display = '';
        document.getElementById('modalAddItem').style.display = 'flex';
    }

    function openEditItem(itemId) {
        const item = state.items.find(i => i.id === itemId);
        if (!item) return;

        editingItemId = itemId;
        itemPhotoData = item.photo || null;
        document.getElementById('itemModalTitle').textContent = t('edit_item');
        document.getElementById('inputItemName').value = item.name;
        document.getElementById('inputItemPrice').value = item.price || '';
        document.getElementById('inputItemDate').value = item.date || '';
        document.getElementById('inputItemBrand').value = item.brand || '';
        document.getElementById('inputItemSerial').value = item.serial || '';
        document.getElementById('inputItemNotes').value = item.notes || '';

        if (item.photo) {
            document.getElementById('photoPreview').src = item.photo;
            document.getElementById('photoPreview').style.display = 'block';
            document.querySelector('#photoUploadArea span').style.display = 'none';
        } else {
            document.getElementById('photoPreview').style.display = 'none';
            document.querySelector('#photoUploadArea span').style.display = '';
        }

        document.getElementById('modalAddItem').style.display = 'flex';
    }

    function saveItem() {
        const name = document.getElementById('inputItemName').value.trim();
        if (!name) return;

        const data = {
            name,
            price: parseFloat(document.getElementById('inputItemPrice').value) || 0,
            date: document.getElementById('inputItemDate').value,
            brand: document.getElementById('inputItemBrand').value.trim(),
            serial: document.getElementById('inputItemSerial').value.trim(),
            notes: document.getElementById('inputItemNotes').value.trim(),
            photo: itemPhotoData,
            roomId: currentRoomId
        };

        if (editingItemId) {
            const idx = state.items.findIndex(i => i.id === editingItemId);
            if (idx >= 0) state.items[idx] = { ...state.items[idx], ...data };
        } else {
            data.id = genId();
            state.items.push(data);
        }

        save();
        renderItems();
        updateTotal();
        renderRooms();
        document.getElementById('modalAddItem').style.display = 'none';
    }

    // === EXPORT ===
    function exportReport() {
        let text = `${t('export_title')}\n${'='.repeat(40)}\n${t('export_date')}: ${new Date().toLocaleDateString()}\n\n`;

        state.rooms.forEach(room => {
            const roomItems = state.items.filter(i => i.roomId === room.id);
            const total = roomItems.reduce((s, i) => s + (i.price || 0), 0);
            text += `${room.icon} ${room.name} (${fmt(total)})\n${'-'.repeat(30)}\n`;

            roomItems.forEach(item => {
                text += `  ${item.name}`;
                if (item.brand) text += ` (${item.brand})`;
                text += ` - ${fmt(item.price)}`;
                if (item.date) text += ` [${item.date}]`;
                if (item.serial) text += ` SN:${item.serial}`;
                text += '\n';
            });
            text += '\n';
        });

        const grand = state.items.reduce((s, i) => s + (i.price || 0), 0);
        text += `${'='.repeat(40)}\n${t('grand_total')}: ${fmt(grand)}\n${t('item_count')}: ${state.items.length}\n${t('export_generated')}`;

        const blob = new Blob([text], { type: 'text/plain' });
        const url = URL.createObjectURL(blob);
        const a = document.createElement('a');
        a.href = url;
        a.download = `homelog-inventory-${new Date().toISOString().split('T')[0]}.txt`;
        a.click();
        URL.revokeObjectURL(url);
    }

    // === VIEW SWITCHING ===
    function switchView(viewId) {
        document.querySelectorAll('.view').forEach(v => v.classList.remove('active'));
        document.getElementById(viewId).classList.add('active');
        document.querySelectorAll('.nav-item').forEach(n => n.classList.remove('active'));
        const navBtn = document.querySelector(`.nav-item[data-view="${viewId}"]`);
        if (navBtn) navBtn.classList.add('active');

        if (viewId === 'viewRooms') renderRooms();
        if (viewId === 'viewSummary') renderSummary();
    }

    // === INIT ===
    function init() {
        load();
        applyI18n();
        renderRooms();
        updateTotal();

        // Nav
        document.querySelectorAll('.nav-item').forEach(btn => {
            btn.addEventListener('click', () => switchView(btn.getAttribute('data-view')));
        });

        // Back button
        document.getElementById('btnBackToRooms').addEventListener('click', () => {
            currentRoomId = null;
            switchView('viewRooms');
        });

        // Add room
        document.getElementById('btnAddRoom').addEventListener('click', openAddRoom);
        document.getElementById('btnCloseAddRoom').addEventListener('click', () => {
            document.getElementById('modalAddRoom').style.display = 'none';
        });
        document.getElementById('modalAddRoom').addEventListener('click', (e) => {
            if (e.target === e.currentTarget) e.currentTarget.style.display = 'none';
        });
        document.querySelectorAll('.icon-opt').forEach(opt => {
            opt.addEventListener('click', () => { selectedIcon = opt.getAttribute('data-icon'); updateIconSelection(); });
        });
        document.getElementById('btnSaveRoom').addEventListener('click', saveRoom);

        // Add item
        document.getElementById('btnAddItem').addEventListener('click', openAddItem);
        document.getElementById('btnCloseAddItem').addEventListener('click', () => {
            document.getElementById('modalAddItem').style.display = 'none';
        });
        document.getElementById('modalAddItem').addEventListener('click', (e) => {
            if (e.target === e.currentTarget) e.currentTarget.style.display = 'none';
        });
        document.getElementById('btnSaveItem').addEventListener('click', saveItem);

        // Photo upload
        document.getElementById('photoUploadArea').addEventListener('click', () => {
            document.getElementById('inputItemPhoto').click();
        });
        document.getElementById('inputItemPhoto').addEventListener('change', (e) => {
            const file = e.target.files[0];
            if (!file) return;
            const reader = new FileReader();
            reader.onload = (ev) => {
                // Resize to save localStorage space
                const img = new Image();
                img.onload = () => {
                    const canvas = document.createElement('canvas');
                    const MAX = 400;
                    let w = img.width, h = img.height;
                    if (w > MAX || h > MAX) {
                        if (w > h) { h = h * MAX / w; w = MAX; }
                        else { w = w * MAX / h; h = MAX; }
                    }
                    canvas.width = w;
                    canvas.height = h;
                    canvas.getContext('2d').drawImage(img, 0, 0, w, h);
                    itemPhotoData = canvas.toDataURL('image/jpeg', 0.7);
                    document.getElementById('photoPreview').src = itemPhotoData;
                    document.getElementById('photoPreview').style.display = 'block';
                    document.querySelector('#photoUploadArea span').style.display = 'none';
                };
                img.src = ev.target.result;
            };
            reader.readAsDataURL(file);
        });

        // Export
        document.getElementById('btnExport').addEventListener('click', exportReport);

        // Language
        document.getElementById('btnLang').addEventListener('click', () => {
            document.getElementById('modalLang').style.display = 'flex';
        });
        document.getElementById('btnCloseLang').addEventListener('click', () => {
            document.getElementById('modalLang').style.display = 'none';
        });
        document.getElementById('modalLang').addEventListener('click', (e) => {
            if (e.target === e.currentTarget) e.currentTarget.style.display = 'none';
        });
        document.querySelectorAll('.lang-btn').forEach(btn => {
            btn.addEventListener('click', () => {
                state.lang = btn.getAttribute('data-lang');
                save();
                applyI18n();
                renderRooms();
                document.getElementById('modalLang').style.display = 'none';
            });
        });
    }

    if (document.readyState === 'loading') document.addEventListener('DOMContentLoaded', init);
    else init();
})();
